<?php
namespace WPMailDesk\Application;

use RuntimeException;
use WPMailDesk\Infrastructure\Database\Repository;
use WPMailDesk\Infrastructure\Mail\ImapClient;
use WPMailDesk\Infrastructure\Mail\SmtpSender;
use WPMailDesk\Infrastructure\Security\Crypto;

final class MailService {
    public function __construct(private Repository $repo,private ImapClient $imap,private SmtpSender $smtp,private Crypto $crypto){}
    public function saveAccount(array $in,int$user):int{
        $email=sanitize_email($in['email']??'');if(!$email)throw new RuntimeException('A valid email address is required.');$this->assertSafeHost((string)($in['imap_host']??''),'IMAP');$this->assertSafeHost((string)($in['smtp_host']??''),'SMTP');
        if((($in['imap_security']??'ssl')==='none'||($in['smtp_security']??'ssl')==='none')&&!apply_filters('wpmd_allow_insecure_mail_transport',false,$in))throw new RuntimeException('Unencrypted IMAP/SMTP transport is disabled by default.');
        $data=array('id'=>absint($in['id']??0),'label'=>sanitize_text_field($in['label']??$email),'email'=>$email,'display_name'=>sanitize_text_field($in['display_name']??''),'provider'=>sanitize_key($in['provider']??'generic'),'auth_type'=>in_array(($in['auth_type']??'password'),array('password','oauth'),true)?$in['auth_type']:'password','username'=>sanitize_text_field($in['username']??$email),'imap_host'=>sanitize_text_field($in['imap_host']??''),'imap_port'=>max(1,min(65535,absint($in['imap_port']??993))),'imap_security'=>in_array(($in['imap_security']??'ssl'),array('ssl','tls','none'),true)?$in['imap_security']:'ssl','smtp_host'=>sanitize_text_field($in['smtp_host']??''),'smtp_port'=>max(1,min(65535,absint($in['smtp_port']??465))),'smtp_security'=>in_array(($in['smtp_security']??'ssl'),array('ssl','tls','none'),true)?$in['smtp_security']:'ssl','sync_enabled'=>empty($in['sync_enabled'])?0:1,'sync_days'=>max(1,min(3650,absint($in['sync_days']??30))),'cache_mode'=>in_array(($in['cache_mode']??'balanced'),array('minimal','balanced','offline'),true)?$in['cache_mode']:'balanced','status'=>'configured');
        if(!empty($in['secret']))$data['secret_enc']=$this->crypto->encrypt((string)$in['secret']);
        return $this->repo->save_account($data,$user);
    }
    public function testAccount(int$id,int$user):array{$a=$this->repo->account($id,$user);if(!$a)throw new RuntimeException('Account not found.');return array('imap'=>$this->imap->test($a),'smtp'=>$this->smtp->test($a));}
    public function syncAccount(int$id,int$user):array{$a=$this->repo->account($id,$user);if(!$a)throw new RuntimeException('Account not found.');$folders=$this->imap->folders($a);foreach($folders as$f)$this->repo->upsert_folder($id,$f);$count=0;foreach($this->repo->folders($id)as$f){if(in_array($f['special_use'],array('\\Inbox','\\Sent','\\Drafts','\\Junk','\\Trash'),true)||'INBOX'===strtoupper($f['remote_name'])){$res=$this->imap->fetchRecent($a,$f['remote_name'],(int)$a['sync_days'],250);$uv=(int)($res['status']['uidvalidity']??$f['uidvalidity']??0);foreach($res['messages']as$m){$this->repo->upsert_message($id,(int)$f['id'],$uv,(int)$m['uid'],$m['message']);$count++;}}} $this->repo->log('sync_account',$id,null,'success',array('messages'=>$count));return array('folders'=>count($folders),'messages'=>$count);}
    public function queueSend(int$accountId,int$user,array$p):int{if(!$this->repo->user_can_access_account($user,$accountId))throw new RuntimeException('Account not accessible.');$this->enforceSendRateLimit($user,$accountId);$to=$this->addresses($p['to']??array());if(!$to)throw new RuntimeException('At least one recipient is required.');$payload=array('to'=>$to,'cc'=>$this->addresses($p['cc']??array()),'bcc'=>$this->addresses($p['bcc']??array()),'reply_to'=>$this->addresses($p['reply_to']??array()),'subject'=>sanitize_text_field($p['subject']??''),'body_html'=>wp_kses_post($p['body_html']??''),'body_text'=>sanitize_textarea_field($p['body_text']??''),'attachments'=>array());$host=parse_url(home_url(),PHP_URL_HOST)?:'wordpress.local';$mid=wp_generate_uuid4().'@'.$host;$scheduled=!empty($p['scheduled_at'])?gmdate('Y-m-d H:i:s',strtotime((string)$p['scheduled_at'])):current_time('mysql',true);return$this->repo->queue_outbox($accountId,$user,$payload,$scheduled,$mid);}
    public function sendOutbox(array$row):void{$a=$this->repo->account((int)$row['account_id']);if(!$a)throw new RuntimeException('Account missing.');$p=json_decode($row['payload_json'],true)?:array();$this->repo->update_outbox((int)$row['id'],array('status'=>'sending','attempts'=>(int)$row['attempts']+1));try{$this->smtp->send($a,$p,$row['message_id_header']);$this->repo->update_outbox((int)$row['id'],array('status'=>'sent','sent_at'=>current_time('mysql',true),'last_error'=>null));$this->repo->log('send_mail',(int)$row['account_id'],null,'success',array('outbox_id'=>(int)$row['id']));}catch(\Throwable$e){$attempts=(int)$row['attempts']+1;$status=$attempts>=5?'failed':'retrying';$delay=min(3600,60*(2**max(0,$attempts-1)));$this->repo->update_outbox((int)$row['id'],array('status'=>$status,'last_error'=>$e->getMessage(),'scheduled_at'=>gmdate('Y-m-d H:i:s',time()+$delay)));throw$e;}}
    private function enforceSendRateLimit(int$user,int$account):void{$key='wpmd_send_rate_'.$user.'_'.$account;$count=(int)get_transient($key);$limit=(int)apply_filters('wpmd_send_rate_limit_per_hour',100,$user,$account);if($count>=$limit)throw new RuntimeException('Hourly sending limit reached.');set_transient($key,$count+1,HOUR_IN_SECONDS);}
    private function assertSafeHost(string$host,string$kind):void{$host=trim($host);if(''===$host)throw new RuntimeException($kind.' host is required.');if((bool)apply_filters('wpmd_allow_private_mail_hosts',false,$host,$kind))return;$lower=strtolower(rtrim($host,'.'));if(in_array($lower,array('localhost','localhost.localdomain'),true)||str_ends_with($lower,'.local'))throw new RuntimeException($kind.' host points to a local/private destination.');$ips=@gethostbynamel($host)?:array();foreach($ips as$ip){if(false===filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE))throw new RuntimeException($kind.' host resolves to a private/reserved IP address.');}}
    private function addresses($input):array{if(is_string($input))$input=preg_split('/[,;]+/',$input);$out=array();foreach((array)$input as$x){if(is_string($x)){$e=sanitize_email(trim($x));if($e)$out[]=array('email'=>$e,'name'=>'');}elseif(is_array($x)){ $e=sanitize_email($x['email']??'');if($e)$out[]=array('email'=>$e,'name'=>sanitize_text_field($x['name']??''));}}return$out;}
}
